services:
  - type: web
    name: bazi-analyzer-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    buildpacks:
      - key: https://github.com/render-inc/render-buildpack-chrome
      - key: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9